---
title: Inventory
execute:
  echo: false
jupyter: python3
---

# Inventory

In [1]:
import pandas

In [2]:
inventory = pandas.read_csv("inventory.csv")
inventory

,id,type,manufacturer,quantity,condition,notes
0,1,electrical motors,Cinequads Special Edition,4,NaN,NaN
1,2,propellors (set of 4),NaN,5,NaN,NaN
2,3,body,NaN,1,NaN,NaN
3,4,li-ion batteries,NaN,2,one is broken,NaN
4,5,ethernet shield 2,Arduino 2,1,NaN,NaN
5,6,switching adapter,CUI Inc,1,NaN,NaN
6,7,frame,NaN,1,NaN,NaN
7,8,GPS Antenna,NaN,2,NaN,NaN
8,9,Flight Controller,NaN,1,NaN,NaN
9,10,Motor Controller,NaN,1,NaN,NaN
10,11,LiPo Battery,HOOVO,2,Good,EC5 Connectors

In [3]:
suppliers =  pandas.read_csv("suppliers.csv")
suppliers

,id,inventory_id,price,delivery_charge,name,country,hyperlink
0,1,11,142.99,0.0,amazon.de,Germany,https://www.amazon.de/dp/B0C9HNQHM2?ref=cm_sw_...

___
<p style="text-align: center;">
©️ Koustubh Sinkar
<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/?ref=chooser-v1">
CC BY-NC-ND 4.0
</a>
<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"
alt="">
<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"
alt="">
<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1"
alt="">
<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
src="https://mirrors.creativecommons.org/presskit/icons/nd.svg?ref=chooser-v1"
alt="">
</p>